### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by gilderlan** [YuheiNakasaka/xvideos_helper#36]
``` ruby
 require 'xvideos_helper'
 adult = XvideosHelper::Client.new
 movie_data = adult.movies_of('http://www.xvideos.com')
```

this code return a empty Hash

**Comment by YuheiNakasaka** [comment]
Thank you for reporting a bug.

I will fix the bug in next version.

**Comment by YuheiNakasaka** [comment]
Fixed version.
https://github.com/YuheiNakasaka/xvideos_helper/releases/tag/v0.0.5
